#include "unity.h"

#include "eeprom_layout.h"

void setUp() {}
void tearDown() {}

static void test_regions_keep_the_deployed_addresses()
{
    TEST_ASSERT_EQUAL_UINT16(0, EEPROM_ACTUATOR_CAL_ADDR);
    TEST_ASSERT_EQUAL_UINT16(26, EEPROM_ACTUATOR_CAL_SIZE);
    TEST_ASSERT_EQUAL_UINT16(32, EEPROM_ROLE_ADDR);
    TEST_ASSERT_EQUAL_UINT16(2, EEPROM_ROLE_SIZE);
    TEST_ASSERT_EQUAL_UINT16(40, EEPROM_IMU_CAL_ADDR);
    TEST_ASSERT_EQUAL_UINT16(26, EEPROM_IMU_CAL_SIZE);
    TEST_ASSERT_EQUAL_UINT16(66, EEPROM_POWER_CAL_ADDR);
    TEST_ASSERT_EQUAL_UINT16(14, EEPROM_POWER_CAL_SIZE);
    TEST_ASSERT_EQUAL_UINT16(80, EEPROM_NEXT_AVAILABLE_ADDR);
}

static void test_regions_do_not_overlap()
{
    TEST_ASSERT_LESS_OR_EQUAL_UINT16(
        EEPROM_ROLE_ADDR,
        EEPROM_ACTUATOR_CAL_ADDR + EEPROM_ACTUATOR_CAL_SIZE);
    TEST_ASSERT_LESS_OR_EQUAL_UINT16(
        EEPROM_IMU_CAL_ADDR,
        EEPROM_ROLE_ADDR + EEPROM_ROLE_SIZE);
    TEST_ASSERT_LESS_OR_EQUAL_UINT16(
        EEPROM_POWER_CAL_ADDR,
        EEPROM_IMU_CAL_ADDR + EEPROM_IMU_CAL_SIZE);
    TEST_ASSERT_LESS_OR_EQUAL_UINT16(
        EEPROM_CAPACITY_BYTES,
        EEPROM_NEXT_AVAILABLE_ADDR);
}

int main()
{
    UNITY_BEGIN();
    RUN_TEST(test_regions_keep_the_deployed_addresses);
    RUN_TEST(test_regions_do_not_overlap);
    return UNITY_END();
}
